### ISSUE TITLE
Sample rate

### ISSUE THREAD

**Issue by donnelic** [nicoell/tm-editor-route#6]
Hello there! first of all, thanks for making this plugin, it's great! love it! but 1 thing i've seen is that it get's laggy fast. Now, i don't have the best pc, but a bit of optimising could be implemented, right? One thing i've discovered is that your plugin takes samples at a consistent speed,  while a speed-based sample rate is way more efficient. for example, you can set the sample rate to be: 0.1 * the speed of the car + 1. This is benefitial, since when you are moving slow, you just need less samples, let alone standing still. you can play around with the formula for the best results of course, but i think that a system like this can make the plugin a whole lot more enjoyable to use.

**Comment by nicoell** [comment]
Hi :) 

Currently, you already have two thresholds to control the sample rate, through the Plugin Settings in the OpenPlanet Setting Menu:
- Settings > Recorder > **"Time Step (ms)"**
   - Default: 500ms.
- Settings > Recorder > **"Position Step (m)"**
   - Default: 1m

A new sample is recorded if either of these thresholds is exceeded, that means:
- either: **>= 500ms** have elapsed since the last sample was recorded.
- or: the car's position has moved **more than 1m**.

If the **car is moving slowly**, the **Time Step** is the main condition that leads to samples being recorded.
If the **car is moving fast**, it's the **Position Step** that leads to samples being recorded..

You can tweak both values to your liking and see if this already covers your suggestion.

I still want to improve the rendering performance and limit the amount of rendered lines dynamically to prevent very high frame times.
